import numpy as np
import smtplib
import random
import time

"""
INPUT NEEDED
"""
names = ['marieke', 'parisa', 'gian', 'wout']
emails = ['mariekevanbrussel@msn.com'] * 4
sender_email = "mariekevanbrussel@outlook.com"
host = 'smtp.office365.com'
port = 587
email_subject = "Drawing straws"
email_opening = "Hi "
email_body =  "You have drawn:"
email_closing = "Good luck and see you there!"
closing_line = "Generated by the straw drawing algorithm"


"""
START OF CODE
"""
emails_dict = dict(zip(names,emails))
draws = [""] * len(names)
draws_dict = dict(zip(names, draws))
random.shuffle(names)

for name in names:
    if names.index(name) != (len(names)-1): #For all but the last name in the list
        index_drawn = names.index(name) + 1
        drawn = names[index_drawn]
        draws_dict[name] = drawn
    else:
        drawn = names[0]
        draws_dict[name] = drawn

password = input(str("Please enter your password: "))
server = smtplib.SMTP(host, port)
server.starttls()
server.login(sender_email, password)
print('Login Succesfull')

for name in names:
    rec_email = emails_dict[name]
    drawn = draws_dict[name]
    message = f'Subject: {email_subject} \n\n {email_opening}{name} \n\n {email_body} \n\n {drawn} \n\n {email_closing} \n\n {closing_line}'
    server.sendmail(sender_email, rec_email, message)
    print(message)
    time.sleep(2)

    




